# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Expertiseum
email      : expertiseum01@gmail.com #this is also the email contact forms will go to
description: "Welcome to Expertiseum , a youth-friendly organization. We're determined to bring out latent talents of young geeks, with a focus on spreading those. Founded in 2021 during global coronavirus pandemic, Expertiseum is managed by a team consisting hardworking and dedicated students.Our motto is to create a platform where people can demonstrate their field of sagacity.We hope that you will always be with us in our journey and support us to achieve our goal. If you have any questions or comments,you can reach us through our email: expertiseum01@gmail.com"
author     : Expertiseum
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

fbappid:

collections:
  portfolio:

markdown: kramdown

sass:
    style: compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"
